import request from '@/utils/request'
import querystring from 'querystring'
export default{
    namespaced:true,
    state:{
        categorys:[]
    },
    mutations:{
        SET_CATEGORYS(state,categorys){
            state.categorys=categorys
        }
    },
    actions:{
        //查询所有栏目
        findAllcategory({commit}){
            request.get('category/findAll').then((res)=>{
            commit('SET_CATEGORYS',res.data)
        })
        },
        //保存栏目信息
        saveCategory({dispatch},categoryForm){
            request({
                method:'POST',
                url:'category/saveOrUpdate',
                'content-type':'application/x-www-form-urlencoded',
                data:querystring.stringify(categoryForm)
            }).then((res)=>{
                dispatch('findAllcategory')
            })
        },
        //删除栏目信息
        deleteCategory({dispatch},id){
            request.get('category/deleteById?id='+id).then((res)=>{
                dispatch('findAllcategory')
            })
        },
        //根据栏目名称查询
        searchCategoryById({commit},categoryForm){
            request({
                method:'POST',
                url:'/category/query',
                'content-type':'application/x-www-form-urlencoded',
                data:querystring.stringify(categoryForm)
            }).then((res)=>{
                commit('SET_CATEGORYS',res.data.list)
            })
        }
    }
}